apiVersion: v1
kind: Service
metadata:
  name: dapr-grpc-service-template
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dapr-grpc-service-template
  type: LoadBalancer
